### PR TITLE
Added another C# wrapper(Covid19Tracker.NET)

### PR DESCRIPTION
**Pull request by egbakou**
Hi,
Thanks for this API.

I added another C# wrapper for the API, and the nuget package is already available here [https://www.nuget.org/packages/Covid19Tracker.NET/](https://www.nuget.org/packages/Covid19Tracker.NET/).
This wrapper contains methods that return objects, which can be easily handled in applications. The await/async best practices are also used.

### CODE REVIEW

**Comment by egbakou** [comment]
Thanks @ExpDev07

**Comment by egbakou** [comment]
Will you update the contributors section in the Readme?

**Comment by ExpDev07** [comment]
@egbakou Oops!! My bad!! Was in a hurry, sorry! Adding you now.

**Comment by ExpDev07** [comment]
@all-contributors please add @egbakou for documentation, tool, and platform.

**Pull request merged**
