### PR TITLE
Added `last_updated` to /v2/latest

### PR DESCRIPTION
**Pull request by whitehat007**
Also added source info field

### CODE REVIEW

**Comment by whitehat007** [comment]
Is it possible to get the time of the last update? If so I think that would be preferable.

We could put it under a meta key, but I feel like that's rather unnecessary for just 1-2 keys--plus, that doesn't conform to the [v1 API](https://github.com/ExpDev07/coronavirus-tracker-api/blob/8293d1825173db6d49cd9f582233fa5ed390379e/app/services/location/jhu.py#L92). Either way works, but I just think it should be consistent (and backward-compatible so it doesn't break workflows).

**Comment by ExpDev07** [comment]
The point of the /v2/ was to introduce major changes. We just have to stay compatible with the current v2 endpoints and not v1 (they are now undocumented but staying for legacy support and not to break apps). 

And yes, it’s possible. You can go into the location.py, and add a computer field which just grabs the latest key in the timelines property (see latest). Then you just gotta make sure to add it to the serialization method dict.

**Comment by ExpDev07** [comment]
Oops, I meant timeline.py, not location. The last_update would technically be apart of the timelines.

However, I agree that it would be better having it attached to the actual location object, in which case we can just store the time when the data was last retrieved from JHU. Either way works, but which one is the best, idk.

**Comment by whitehat007** [comment]
Alright, then adding the meta key is the way to go.

I looked at the return data from the timelines property, but the timestamp is always at midnight GMT, which isn't really useful. However, the `Last update` field [here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-18-2020.csv) shows the latest update by country, which would be very useful (and can be attached to the location object). For the case of `/v2/latest`, we could just take the most recent date/time from that field and use that.

**Comment by ExpDev07** [comment]
Yup, it’s always midnight. JHU updates their data only once a day anyways.

**Review by web-sys1 — APPROVED** [review]

**Comment by Kilo59** [comment]
Will be adding a similar feature, hopefully soon.

**Pull request closed without merging**
