### PR TITLE
V1 to fast api

### PR DESCRIPTION
**Pull request by ibhuiyan17**
Completed transfer of v1 to use FastAPI and passing the currently existing tests. As of this PR, it works as 2 separate routers for v1 and v2 which are imported in main.py as v1router and v2router. These are then added to APP with APP.include_router(v1router, prefix=""), etc. If you guys had a different design in mind, please let me know.

### CODE REVIEW

**Comment by ibhuiyan17** [comment]
Not sure why it failed the build. Any tips on this?

**Comment by ExpDev07** [comment]
Hey! The tests are failing because you haven't run the formatters:

``pipenv shell``
``pipenv run sort``
``pipenv run fmt``

**Comment by ExpDev07** [comment]
Well done, and youve tested that the endpoints work?

**Comment by ibhuiyan17** [comment]
Yep, looks to be working on my end

**Comment by ExpDev07** [comment]
@all-contributors please add @ibhuiyan17 for code.

**Pull request merged**
