### PR TITLE
Add ability to filter aggregate data

### PR DESCRIPTION
**Pull request by SeanCena**
A very very minimal edit, but it would allow users to get aggregate data by country_code, province, etc. by adding a filter as a GET parameter. `GET /api/v2/latest?country_code=US` would solve #108 , for instance.

### CODE REVIEW

**Comment by ExpDev07** [comment]
I really like the way this was solved, nicely done. This should probably be documented in the README.md under the /latest endpoint :).

**Comment by ExpDev07** [comment]
Also, not a 100% sure if /latest should be responsible for the aggregation. Maybe it should instead be moved to /locations, and be put under “aggregated” or “latest” top-level?

**Comment by gribok** [comment]
How is about testcases?

**Comment by ExpDev07** [comment]
@gribok *that* - i do not know XD

**Comment by SeanCena** [comment]
Not sure about testcases. I'm not really sure what you mean by aggregated or latest top-level, would you mind explaining in more detail?

**Comment by ExpDev07** [comment]
Like this:
```HTTP
/v2/locations?country_code=US
```

returns
```json
{
  "latest": {
      "confirmed": 100000,
      "deaths": 4000,
      "recovered": 70000
  },
  "locations": [
  ]
}
```

"latest" being the sum of all the latest from all the locations returned (aggregated). Not sure whether we should call it latest or aggregated though.

And it's okay aha @SeanCena

**Comment by ExpDev07** [comment]
Very nicely done! Could you perhaps rename it to "latest" instead? I think overall it would make more sense given that's what it's called inside the locations.

**Comment by SeanCena** [comment]
Thanks, I moved the latest() code to locations(). For now, I put the aggregate data under "aggregate". Also, one of the side effects is that you can now pass any attribute (not just country_code) as an argument to /locations, which I just realized includes the double-underscore attributes of the timelinedlocations class. Might be a security issue, idk? Other than that, everything seems to work fine. `make tests` fails because there is no __main__ module apparently.

**Comment by ExpDev07** [comment]
Thanks a lot! Looks good. Merging.

**Comment by ExpDev07** [comment]
@all-contributors please add @SeanCena for code, documentation, and tests.

**Pull request merged**
