### PR TITLE
Api docs changes

### PR DESCRIPTION
**Pull request by carmelag**
Please review the new structure of the API documentation. Any feedback or request to make some changes is welcome. 

❗Something important is missing in the documentation, it's the place where the developers can get the list of available and valid ids for locations if they want to use the locations endpoint with the path parameter _:id._
I would like to add this information, but I wasn't able to find it anywhere.

Looking forward to hearing from you, owner and collaborators.
Thanks in advance for your help.

### CODE REVIEW

**Comment by ExpDev07** [comment]
The :id (IDs) can be found in the locations response. Thailand has an ID of 0 and can be seen at ``/v2/locations/0``.

**Comment by ExpDev07** [comment]
Thank you so much for this! Merging.

**Comment by ExpDev07** [comment]
@all-contributors please add @carmelag for documentation.

**Comment by carmelag** [comment]
Happy to help with this project! 🤗

**Pull request merged**
