### PR TITLE
Add Swagger 2.0 API documentation

### PR DESCRIPTION
**Pull request by oliver-xapix-io**

### CODE REVIEW

**Comment by oliver-xapix-io** [comment]
No code needed on your end. You would need to update the swagger file if you plan to add more endpoints or change the the existing ones (please don't).

You can hand that swagger file out to interested people and they can load it with their fav tools like postman, soap ui, etc.

If you wanna put up a website at some point you can also just integrate the swagger-UI javascript library snippet with that swagger and it auto generates a full blown live test interface. if you paste the content into editor.swagger.io you'll see what i am talking about (right side). Your API instance and the website should be in the same domain though otherwise swagger UI will give you the normal CORS issues.

You could also upload it to the apis.guru swagger file catalogue so other people can find you.

**Comment by oliver-xapix-io** [comment]
Maybe one remark: I reverse engineered it from the responses I saw. So maybe give it a second look or add some more explanations as needed, I just spent today with your api, so I am not an expert

**Comment by ExpDev07** [comment]
Hey @allcontributors, add @oliver-xapix-io for documentation.

**Comment by ExpDev07** [comment]
Hey @all-contributors please add @oliver-xapix-io for documentation.

**Pull request merged**
