### PR TITLE
Improve doc: The data is cached for 1 hour

### PR DESCRIPTION
**Pull request by Bost**

### CODE REVIEW

**Comment by ExpDev07** [comment]
all-contributors add @BostX for documentation.

**Comment by ExpDev07** [comment]
@ all-contributors add @Bost for documentation.

**Comment by ExpDev07** [comment]
@all-contributors add @Bost for documentation.

**Comment by Bost** [comment]
FYI the story might not be over so quickly https://github.com/tkem/cachetools/pull/161

**Pull request merged**
